src/Entity/Producer.php
<?php

namespace App\Entity;

use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Exception;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProducerRepository")
 * @Vich\Uploadable()
 */
class Producer
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $siret;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firm_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firm_adress;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $firm_postal_code;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $firm_city;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="producer_image", fileNameProperty="image")
     *
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     *
     * @var string|null
     */
    private $image;


    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\ProductionType")
     * @ORM\JoinColumn(nullable=false)
     */
    private $production_type;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\User", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Good", mappedBy="producer")
     */
    private $goods;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $phone_number;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @var DateTimeInterface|null
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $tva_intracom;

    public function __construct()
    {
        $this->goods = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSiret(): ?string
    {
        return $this->siret;
    }

    public function setSiret(string $siret): self
    {
        $this->siret = $siret;

        return $this;
    }

    public function getFirmName(): ?string
    {
        return $this->firm_name;
    }

    public function setFirmName(string $firm_name): self
    {
        $this->firm_name = $firm_name;

        return $this;
    }

    public function getFirmAdress(): ?string
    {
        return $this->firm_adress;
    }

    public function setFirmAdress(string $firm_adress): self
    {
        $this->firm_adress = $firm_adress;

        return $this;
    }

    public function getFirmPostalCode(): ?string
    {
        return $this->firm_postal_code;
    }

    public function setFirmPostalCode(string $firm_postal_code): self
    {
        $this->firm_postal_code = $firm_postal_code;

        return $this;
    }

    public function getFirmCity(): ?string
    {
        return $this->firm_city;
    }

    public function setFirmCity(string $firm_city): self
    {
        $this->firm_city = $firm_city;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|UploadedFile|null $imageFile
     * @throws Exception
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): void
    {
        $this->image = $image;

    }

    public function getProductionType(): ?ProductionType
    {
        return $this->production_type;
    }

    public function setProductionType(?ProductionType $production_type): self
    {
        $this->production_type = $production_type;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Good[]
     */
    public function getGoods(): Collection
    {
        return $this->goods;
    }

    public function addGood(Good $good): self
    {
        if (!$this->goods->contains($good)) {
            $this->goods[] = $good;
            $good->setProducer($this);
        }

        return $this;
    }

    public function removeGood(Good $good): self
    {
        if ($this->goods->contains($good)) {
            $this->goods->removeElement($good);
            // set the owning side to null (unless already changed)
            if ($good->getProducer() === $this) {
                $good->setProducer(null);
            }
        }

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(string $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getUpdatedAt(): ?DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getTvaIntracom(): ?string
    {
        return $this->tva_intracom;
    }

    public function setTvaIntracom(string $tva_intracom): self
    {
        $this->tva_intracom = $tva_intracom;

        return $this;
    }
}

src/Form/ProducerType.php
<?php

namespace App\Form;

use App\Entity\Producer;
use App\Entity\ProductionType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichImageType;


class ProducerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('siret')
            ->add('firm_name')
            ->add('firm_adress')
            ->add('firm_postal_code')
            ->add('firm_city')
            ->add('description')
            ->add('imageFile', VichImageType::class, [
                'required' => false,
            ])
            ->add('phone_number')
            ->add('production_type', EntityType::class, [
                'class' => ProductionType::class,
                'required' => true,
                'label' => 'Votre type de production principal',
                'choice_label' => 'label',
                'multiple' => false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Producer::class,
        ]);
    }
}

src/Controller/ProducerController.php
<?php

namespace App\Controller;

use App\Entity\LabelledType;
use App\Entity\Producer;
use App\Entity\User;
use App\Form\LabelledTType;
use App\Form\ProducerType;
use App\Repository\ProducerRepository;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/producer")
 */
class ProducerController extends AbstractController
{
    /**
     * @Route("/", name="producer_index", methods={"GET"})
     * @param PaginatorInterface $paginator
     * @param Request $request
     * @return Response
     */
    public function index(PaginatorInterface $paginator, Request $request): Response
    {
        $producers = $paginator->paginate(
            $this
                ->getDoctrine()
                ->getRepository( Producer::class)
                ->findAll(),
            $request
                ->query->getInt('page', 1),
            8

        );

        return $this->render('producer/index.html.twig', [
            'producers' => $producers,
        ]);
    }

    /**
     * @Route("/mes-producteurs", name="producer_showMyProducers", methods={"GET"})
     * @param PaginatorInterface $paginator
     * @param Request $request
     * @return Response
     */
    public function showMyProducers(PaginatorInterface $paginator, Request $request): Response
    {

        $myProducers = $this
            ->getDoctrine()
            ->getRepository(User::class)
            ->findBy(array('trade_area' => $this->getUser()->getTradeArea()->getId()));

        $producers = $paginator->paginate(
            $producers = $this
            ->getDoctrine()
            ->getRepository(Producer::class)
            ->findBy(array('user' => $myProducers)),

            $request
                ->query->getInt('page', 1),
            8

        );

        return $this->render('producer/myProducer.html.twig', [
            'producers' => $producers,
        ]);
    }

    /**
     * @Route("/new", name="producer_new", methods={"GET","POST"})
     * @param Request $request
     * @return Response
     */
    public function new(Request $request): Response
    {
        $producer = new Producer();
        $user = $this->getUser();
        $form = $this->createForm(ProducerType::class, $producer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $producer->setUser($user);

            $entityManager->persist($producer);
            $entityManager->flush();

            return $this->redirectToRoute('producer_index');
        }

        return $this->render('producer/new.html.twig', [
            'producer' => $producer,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="producer_show", methods={"GET"})
     */
    public function show(Producer $producer): Response
    {
        return $this->render('producer/show.html.twig', [
            'producer' => $producer,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="producer_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Producer $producer): Response
    {
        $form = $this->createForm(ProducerType::class, $producer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('producer_index');
        }

        return $this->render('producer/edit.html.twig', [
            'producer' => $producer,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="producer_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Producer $producer): Response
    {
        if ($this->isCsrfTokenValid('delete'.$producer->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($producer);
            $entityManager->flush();
        }

        return $this->redirectToRoute('producer_index');
    }

}

templates/producer/_delete_form.html.twig
<form method="post" action="{{ path('producer_delete', {'id': producer.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ producer.id) }}">
    <button class="btn btn-danger text-white mt-2 mr-4 ml-auto">Supprimer le producteur</button>
</form>

templates/producer/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/producer/_menu.html.twig
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Accueil</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor02">
        <ul class="navbar-nav mr-auto">
            <li>
                <a class="nav-link" href="#">A propos</a>
            </li>
            <li class="nav-item mr-sm-2">
                <a class="nav-link btn btn-success text-white" type="button" href="{{ path('user_new') }}" data-toggle="modal" data-target="#myModal">S'enregistrer</a>
            </li>
            <li class="nav-item mr-sm-2 ">
                <a class="nav-link btn btn-primary text-white" type="button" href="/login" data-toggle="modal" data-target="#myModal">Se Connecter</a>
            </li>
        </ul>

    </div>
</nav>
<img src="{{ asset('images/bg.jpg')}}" class="img-fluid" alt="" />

templates/producer/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Producer{% endblock %}

{% block body %}
    <h1>Edit Producer</h1>

    {{ include('producer/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('producer_index') }}">back to list</a>

    {{ include('producer/_delete_form.html.twig') }}
{% endblock %}

templates/producer/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Producer index{% endblock %}

{% block body %}

    {{ include('home/_menu.html.twig') }}

    <h2 class="">Tous nos producteurs :</h2>

    <div class="container">
        <div class="row row-cols-4">

    {% for producer in producers %}
        <a href="{{ path('producer_show', {'id': producer.id}) }}"><div class="col mt-4">
                <div><img class="img-thumbnail img-producers" src="{{ asset('images/producers/' ~ producer.image)}}" alt="image de {{ producer.FirmName }}"></div>
                <h5 class="mb-2">{{ producer.firmName }}</h5>
                <button type="button" class="btn-sm btn-primary" data-toggle="modal" data-target="#{{ producer.id }}Modal">détails</button>
            </div></a>
        <div class="modal fade" id="{{ producer.id }}Modal" tabindex="-1" role="dialog" aria-labelledby="{{producer.id}}ModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="{{ producer.id }}ModalLongTitle">Fiche de {{ producer.firmName }}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="mt-3">{{ producer.description }}</div>
                        <div class="mt-3">Vous pouvez retrouver ce producteur au:<br> {{ producer.firmAdress }}, {{ producer.firmCity }} ({{ producer.firmPostalCode }})</div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn-sm btn-secondary" data-dismiss="modal">Fermer</button>
                    </div>
                </div>
            </div>
        </div>

    {% endfor %}

            </div>
        <div class="row justify-content-md-center mt-5">
                <div class="navigation">
                    {{ knp_pagination_render(producers) }}
                </div>
        </div>

    </div>



    <a href="{{ path('producer_new') }}">Create new</a>


{% endblock %}

templates/producer/myProducer.html.twig
{% extends 'base.html.twig' %}

{% block title %}Producer index{% endblock %}

{% block body %}

    {{ include('home/_menu.html.twig') }}

    <h2 class="">Tous nos producteurs :</h2>

    <div class="container">
        <div class="row row-cols-4">

            {% for producer in producers %}
                <div class="col mt-4">
                    <div><img class="img-thumbnail img-producers" src="{{ asset('images/producers/' ~ producer.image)}}" alt="image de {{ producer.FirmName }}"></div>
                    <h5 class="mb-2">{{ producer.firmName }}</h5>
                    <button type="button" class="btn-sm btn-primary" data-toggle="modal" data-target="#{{ producer.id }}Modal">détails</button>
                </div>
                <div class="modal fade" id="{{ producer.id }}Modal" tabindex="-1" role="dialog" aria-labelledby="{{producer.id}}ModalCenterTitle" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="{{ producer.id }}ModalLongTitle">Fiche de {{ producer.firmName }}</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <div class="mt-3">{{ producer.description }}</div>
                                <div class="mt-3">Vous pouvez retrouver ce producteur au:<br> {{ producer.firmAdress }}, {{ producer.firmCity }} ({{ producer.firmPostalCode }})</div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn-sm btn-secondary" data-dismiss="modal">Fermer</button>
                            </div>
                        </div>
                    </div>
                </div>

            {% endfor %}

        </div>
        <div class="row justify-content-md-center mt-5">
            <div class="navigation">
                {{ knp_pagination_render(producers) }}
            </div>
        </div>

    </div>



    <a href="{{ path('producer_new') }}">Create new</a>


{% endblock %}

templates/producer/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau Producteur{% endblock %}

{% block body %}
    <h1>Créer votre page producteur/h1>

    {{ include('producer/_form.html.twig') }}

    <a href="{{ path('producer_index') }}">Retour</a>
{% endblock %}

templates/producer/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Producer{% endblock %}

{% block body %}
    <h1>Producer</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ producer.id }}</td>
            </tr>
            <tr>
                <th>Siret</th>
                <td>{{ producer.siret }}</td>
            </tr>
            <tr>
                <th>Firm_name</th>
                <td>{{ producer.firmName }}</td>
            </tr>
            <tr>
                <th>Firm_adress</th>
                <td>{{ producer.firmAdress }}</td>
            </tr>
            <tr>
                <th>Firm_postal_code</th>
                <td>{{ producer.firmPostalCode }}</td>
            </tr>
            <tr>
                <th>Firm_city</th>
                <td>{{ producer.firmCity }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ producer.description }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ producer.image }}</td>
            </tr>
            <tr>
                <th>Phone_number</th>
                <td>{{ producer.phoneNumber }}</td>
            </tr>
        </tbody>
    </table>
    <div class="ml-4">
    <a class=" btn btn-info text-white" type="button" href="{{ path('producer_index') }}">Retour</a>

    {% if producer.user.id == app.user.id or is_granted('ROLE_ADMIN') %}
        <a class=" btn btn-danger text-white" type="button" href="{{ path('producer_edit', {'id': producer.id}) }}">Modifier</a>
    {% endif %}

    {% if is_granted('ROLE_ADMIN') %}
        {{ include('producer/_delete_form.html.twig') }}
    {% endif %}
    </div>
{% endblock %}