src/Entity/Profile.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProfileRepository")
 */
class Profile
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Serializable;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface, Serializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Role")
     * @ORM\JoinColumn(nullable=false)
     */
    private $role;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Profile", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $profile;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\TradeArea")
     * @ORM\JoinColumn(nullable=false)
     */
    private $trade_area;

    /**
     * @ORM\OneToMany(targetEntity=Subscription::class, mappedBy="user")
     */
    private $subscriptions;

    /**
     * @ORM\OneToMany(targetEntity=Facture::class, mappedBy="user")
     */
    private $factures;

    /**
     * @ORM\OneToMany(targetEntity=Facture::class, mappedBy="customer")
     */
    private $customers;

    /**
     * @ORM\OneToMany(targetEntity=Association::class, mappedBy="user")
     */
    private $associations;

    public function __construct()
    {
        $this->subscriptions = new ArrayCollection();
        $this->factures = new ArrayCollection();
        $this->customers = new ArrayCollection();
        $this->associations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getRole(): ?Role
    {
        return $this->role;
    }

    public function setRole(?Role $role): self
    {
        $this->role = $role;

        return $this;
    }

    public function getProfile(): ?Profile
    {
        return $this->profile;
    }

    public function setProfile(Profile $profile): self
    {
        $this->profile = $profile;

        return $this;
    }

    public function getTradeArea(): ?TradeArea
    {
        return $this->trade_area;
    }

    public function setTradeArea(?TradeArea $trade_area): self
    {
        $this->trade_area = $trade_area;

        return $this;
    }

    /**
     * @inheritDoc
     */
    public function getRoles()
    {
        return [ $this->role->getLabel() ];
    }

    /**
     * @inheritDoc
     */
    public function getSalt()
    {
        return '3k0L4b3!';
    }

    /**
     * @inheritDoc
     */
    public function getUsername()
    {
        return $this->email;
    }

    /**
     * @inheritDoc
     */
    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    /**
     * @inheritDoc
     */
    public function serialize()
    {
        return serialize([
            $this->id,
            $this->email,
            $this->password,
        ]);
    }

    /**
     * @inheritDoc
     */
    public function unserialize($serialized)
    {
        list($this->id,
            $this->email,
            $this->password) = unserialize($serialized, ['allowed_classes'=> false]);
    }

    /**
     * @return Collection|Subscription[]
     */
    public function getSubscriptions(): Collection
    {
        return $this->subscriptions;
    }

    public function addSubscription(Subscription $subscription): self
    {
        if (!$this->subscriptions->contains($subscription)) {
            $this->subscriptions[] = $subscription;
            $subscription->setUser($this);
        }

        return $this;
    }

    public function removeSubscription(Subscription $subscription): self
    {
        if ($this->subscriptions->removeElement($subscription)) {
            // set the owning side to null (unless already changed)
            if ($subscription->getUser() === $this) {
                $subscription->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Facture[]
     */
    public function getFactures(): Collection
    {
        return $this->factures;
    }

    public function addFacture(Facture $facture): self
    {
        if (!$this->factures->contains($facture)) {
            $this->factures[] = $facture;
            $facture->setUser($this);
        }

        return $this;
    }

    public function removeFacture(Facture $facture): self
    {
        if ($this->factures->removeElement($facture)) {
            // set the owning side to null (unless already changed)
            if ($facture->getUser() === $this) {
                $facture->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Facture[]
     */
    public function getCustomers(): Collection
    {
        return $this->customers;
    }

    public function addCustomer(Facture $customer): self
    {
        if (!$this->customers->contains($customer)) {
            $this->customers[] = $customer;
            $customer->setCustomer($this);
        }

        return $this;
    }

    public function removeCustomer(Facture $customer): self
    {
        if ($this->customers->removeElement($customer)) {
            // set the owning side to null (unless already changed)
            if ($customer->getCustomer() === $this) {
                $customer->setCustomer(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Association[]
     */
    public function getAssociations(): Collection
    {
        return $this->associations;
    }

    public function addAssociation(Association $association): self
    {
        if (!$this->associations->contains($association)) {
            $this->associations[] = $association;
            $association->setUser($this);
        }

        return $this;
    }

    public function removeAssociation(Association $association): self
    {
        if ($this->associations->removeElement($association)) {
            // set the owning side to null (unless already changed)
            if ($association->getUser() === $this) {
                $association->setUser(null);
            }
        }

        return $this;
    }

}

src/Controller/HomeController.php
<?php


namespace App\Controller;


use App\Entity\Good;
use App\Entity\GoodsType;
use App\Entity\LabelledType;
use App\Entity\Producer;
use App\Entity\Profile;
use App\Entity\Trimester;
use App\Entity\UnitType;
use App\Entity\User;
use App\Form\GoodsTType;
use App\Form\LabelledTType;
use App\Form\UnitTType;
use DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class HomeController extends AbstractController
{

    /**
     * @Route("/", name="home")
     */
    public function index()
    {
        $producers = $this
            ->getDoctrine()
            ->getRepository(Producer::class)
            ->getNb();

        $goods = $this
            ->getDoctrine()
            ->getRepository(Good::class)
            ->getNb();

        $users = $this
            ->getDoctrine()
            ->getRepository(User::class)
            ->findAll();


        $meASProd = $this
            ->getDoctrine()
            ->getRepository(Producer::class)
            ->findOneBy(array('user' => $this->getUser()));
        dump($meASProd);

        $myGoods = $this
            ->getDoctrine()
            ->getRepository(Good::class)
            ->findBy(array('producer' => $meASProd));
        dump($myGoods);

        $isUser = $this->getUser();
        if (isset($isUser)) {

            $prodProfile = $this
                ->getDoctrine()
                ->getRepository(Producer::class)
                ->findOneBy(array('user' => $this->getUser()->getId()));
        }else {$prodProfile = 'On en est là';}

        return $this->render('home/index.html.twig', [
            'producers' => $producers,
            'goods' => $goods,
            'users' => $users,
            'prodProfile' => $prodProfile
        ]);
    }

    /**
     * @Route("/charte", name="charte", methods={"GET"})
     * @return Response
     */
    public function showCharte(): Response
    {

        return $this->render('home/charte.html.twig');
    }


    /**
     * @Route("/login", name="login")
     * @param AuthenticationUtils $authenticationUtils
     * @return Response
     */
    public function login( AuthenticationUtils $authenticationUtils ) {
        $error = $authenticationUtils->getLastAuthenticationError();
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render("home/login.html.twig", [
            'last_username' => $lastUsername,
            'error' => $error,
        ]);
    }

    /**
     * @Route("/profile", name="profile", methods={"GET"})
     * @return Response
     */
    public function profile()
    {
        $profile = $this
            ->getDoctrine()
            ->getRepository(Profile::class)
            ->find($this->getUser()->getProfile());


        return $this->render("home/profile.html.twig", [
            'profile' => $profile
        ]);
    }

    /**
     * @Route("/nouveau-label", name="good_newLabel", methods={"GET","POST"})
     * @param Request $request
     * @return Response
     */
    public function newLabel(Request $request): Response
    {
        $label = new LabelledType();
        $form = $this->createForm(LabelledTType::class, $label);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();

            $entityManager->persist($label);
            $entityManager->flush();

            return $this->redirectToRoute('good_new');
        }

        return $this->render('good/newLabel.html.twig', [
            'label' => $label,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/nouveau-type-produit", name="good_newProductType", methods={"GET","POST"})
     * @param Request $request
     * @return Response
     */
    public function newProductType(Request $request): Response
    {
        $goodsType = new GoodsType();
        $form = $this->createForm(GoodsTType::class, $goodsType);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();

            $entityManager->persist($goodsType);
            $entityManager->flush();

            return $this->redirectToRoute('good_new');
        }

        return $this->render('good/newProductType.html.twig', [
            'goodsType' => $goodsType,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/nouvelle-unite", name="good_newUnit", methods={"GET","POST"})
     * @param Request $request
     * @return Response
     */
    public function newUnit(Request $request): Response
    {
        $unit = new UnitType();
        $form = $this->createForm(UnitTType::class, $unit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();

            $entityManager->persist($unit);
            $entityManager->flush();

            return $this->redirectToRoute('good_new');
        }

        return $this->render('good/newUnit.html.twig', [
            'unit' => $unit,
            'form' => $form->createView(),
        ]);
    }




}

templates/home/_menu.html.twig
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Accueil</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor02">
        <ul class="navbar-nav mr-auto">

            <li>
                <a class="nav-link" href="{{ path('charte') }}">Notre charte</a>
            </li>
            {% if is_granted('ROLE_USER') %}
                <li>
                    <a class="nav-link" href="#">Les produits</a>
                </li>
                {% endif %}
            {% if is_granted('ROLE_PRODUCER') %}
                <li>
                    <a class="nav-link" href="#">Mes produits</a>
                </li>
                <li>
                    <a class="nav-link" href="#">Mes factures</a>
                </li>
            {% endif %}

            {% if is_granted('IS_AUTHENTICATED_FULLY') %}

                <li>
                    <a class="nav-link" href="{{ path('producer_index') }}">Les producteurs</a>
                </li>
                {% if is_granted('ROLE_ADMIN') %}

                    <li>
                        <a class="nav-link" href="{{ path('stats') }}">Clients</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{{ path('stats') }}">Factures</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{{ path('stats') }}">Livraisons</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{{ path('stats') }}">Bonus/Malus</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{{ path('stats') }}">Tarif/Taxe</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{{ path('stats') }}">Statistiques</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{{ path('stats') }}">Association</a>
                    </li>

                {% else %}
                    <li>
                        <a class="nav-link" href="{{ path('profile') }}">Mon profil</a>
                    </li>
                {% endif %}

                {% if is_granted('ROLE_USER') %}
                    <li>
                        <a class="nav-link" href="{{ path('subscription_myorders') }}">Mes commandes</a>
                    </li>
                    <a class="nav-link btn btn-success text-white mr-2" type="button" href="{{ path('subscription_new') }}">Je commande !</a>
                {% endif %}
                <li class="nav-item mr-sm-2">
                    <a class="nav-link btn btn-danger text-white ml-1" type="button" href="{{ path('logout') }}">Déconnexion</a>
                </li>

            {% else %}
                <li class="nav-item mr-sm-2">
                    <a class="nav-link btn btn-success text-white" type="button" href="{{ path('user_new') }}">S'inscrire</a>
                </li>
                <li class="nav-item mr-sm-2 ">
                    <a class="nav-link btn btn-primary text-white" type="button" href="{{ path('login') }}">Se Connecter</a>
                </li>
            {% endif %}
        </ul>

    </div>
</nav>
{# <img src="{{ asset('images/bg.jpg')}}" class="img-fluid" alt="" /> #}

templates/home/charte.html.twig
{% extends 'base.html.twig' %}


{% block body %}

    {{ include('home/_menu.html.twig') }}
    <div class="container">

        <h1 class="text-md-center mt-2 mb-4">Notre charte en bref</h1>

        <h3>A. Principes généraux</h3>

        <p>
            Val Llech est une association à but non lucratif qui cherche à promouvoir le bien-vivre ensemble
            au sein de la vallée du Llech dans le respect de l’environnement.
            Ce credo sert de socle à un effort collectif pour harmoniser à l’échelle de la vallée les trois piliers
            du développement durable : l’écologie (préservation, respect, amélioration, valorisation),
            le social (ouverture, convivialité, solidarité, générosité)
            et l’économie (complémentarité, mutualisation, innovation, accompagnement).
            Cette recherche de durabilité fait office de tronc commun à l’ensemble de nos actions,
            lesquelles sont organisées selon des commissions.
        </p>

        <p>
            On peut se représenter le fonctionnement de l’association à la manière d’un arbre dont
            les racines s’assimilent à la mission, le tronc au cadre de valeur de la durabilité,
            les branches aux commissions et les feuilles aux actions (voir figure 1).
        </p>

        <img style="margin-left: 30%" class="mt-2 mb-2"  src="https://1.bp.blogspot.com/-5exVC6ZWct0/XymDqM7uosI/AAAAAAAAAEc/NHz6NUpFQ9gX1CSeACsmWzQKqF1GaydfACLcBGAsYHQ/s0/arbre%2BVL.png" alt="représentation arbre">

        <p>
            Le flux de sève qui fait vivre cet arbre est la somme des énergies individuelles qui
            se mobilisent pour le collectif. Des allers-retours permanents doivent être faits entre les racines
            (mission) et les feuilles (activités) tel un flux de sève.
            Ca se traduit comme suit : une idée bourgeonne, devient une branche (commission)
            et donne des fruits (actions). A l’opposé, une branche qui cesse d’être irriguée par la sève (nous) meurt.
            Dans ce sens l’association est une plateforme qui peut permettre à tout un chacun de développer
            sa créativité à partir du moment où celle-ci est collectivement considérée comme durable.
            Le collectif se met alors au service de l’individu à condition que ce dernier soit au service du collectif.
        </p>
        <h3>B. Traduction concrète</h3>

        <p>
            Chacune des branches, et donc des feuilles est tributaire du tronc :
            pour chaque action nous devons pouvoir dire en quoi elle participe au bien-être social et/ou environnemental
            sans mettre en cause les activités économiques voire en les confortant (figure 2).
        </p>

        <img style="margin-left: 30%" class="mt-2 mb-2"  src="https://1.bp.blogspot.com/-SztOLHFjGME/XymEfwMn_vI/AAAAAAAAAEk/Yq0PpoJBHywWY2rvWooEvgtAZ86N3KJJACLcBGAsYHQ/s0/couronne%2Basso.png" alt="Couronne d'action de l'association">

        <p>
            Ainsi, les marchés construisent du lien entre les habitants en (i)
            offrant l’accès à des produits de proximité, (ii) en permettant l’écoulement de leur production
            aux agriculteurs et (iii) en créant des espaces de convivialité / festivités.
            La dimension environnementale est pour l’instant couverte par le raccourcissement
            des circuits de distribution et sera renforcée par la création du label qui invitera chacun à s’inscrire
            dans une démarche de progrès.
        </p>

        <p>
            Les événements organisés par l’association ont pour objet (i) la sensibilisation
            à différentes thématiques ayant trait au développement durable, (ii) la mise en réseau
            de l’association avec d’autres associations du Conflent qui poursuivent des objectifs proches,
            et/ou (iii) des propositions culturelles absentes jusqu’alors (projections / débats etc.).
        </p>

        <p>
            Enfin, la création d’un système participatif de garantie (SPG)
            ouvert à toutes celles et ceux qui souhaitent entrer dans une démarche collective d’amélioration
            de notre rapport à l’environnement et de solidarité.
            Il s’agira d’un socle commun qui pourrait dans un second temps être valorisé pour
            les différentes activités économiques présentes dans la vallée et éventuellement appuyer
            de nouvelles créations.
        </p>

        <h3>C- Le pilotage de l’association</h3>

        <p>
            La prise de décision au sein de l’association se construit à trois niveaux interdépendants.
            Tout d’abord les Assemblées Générales annuelles. Les AG rassemblent l’ensemble des adhérents de l’association.
            En plus des questions « normées » que toute association doit traiter dans cet espace
            (à savoir un compte rendu des comptes de l’association et des actions menées),
            c’est à ce moment que peuvent être discutées la mission et les valeurs portées par l’association.
            Il s’agit de la seule instance disposant du pouvoir de changement au niveau racinaire et du tronc.
        </p>

        <p>
            Ensuite viennent les Conseils d’Administration mensuels ou bimestriels.
            Ces CA ont pour objet le suivi du bon fonctionnement des commissions. Dans cet espace sont présents
            les membres du conseil d’administration mais peuvent également participer toutes celles et ceux qui
            participent au fonctionnement desdites commissions. Le CA est donc un organe de suivi et d’évaluation.
            Les commissions y présentent leurs avancées respectives et proposent des actions qui seront soumises
            au vote du conseil. C’est à ce moment que de nouvelles propositions peuvent émerger.
            Une proposition ne se traduit en commission qu’à partir du moment où elle est validée par le CA
            et que quelqu’un accepte d’en porter la responsabilité. Pour le moment le fonctionnement admis est le consensus.
            Un fonctionnement à majorité qualifiée pourra être mis en œuvre si nécessaire.
            Ses modalités feront alors l’objet d’une discussion indépendante.
        </p>

        <p>
            Enfin, les commissions qui, indépendantes dans leur fonctionnement, sont chargées de la mise en œuvre
            des actions. Les commissions sont indépendantes dans le sens où elles choisissent elles-mêmes de leur
            rythme de rencontre, sans pour autant perdre de vue l’ambition collective
            (par exemple la commission charte devait arriver à des résultats avant la prochaine AG,
            ce qui conditionnât son rythme propre). Chaque commission doit donc pouvoir gérer seule son calendrier.
            Si des actions d’ordre collectif sont nécessaires au bon déroulé des objectifs qu’elle se fixe,
            la proposition concrète est soumise au CA, et c’est à ce moment que seront visibles les énergies
            disponibles pour faire avancer les choses ou non.
        </p>

        <img style="margin-left: 30%" class="mt-2 mb-2" src=https://1.bp.blogspot.com/-MVrIRtma9vI/XymFDcxYZaI/AAAAAAAAAEw/N9q465y9RvA3cHYCLWq5wuUlwtqj0PlXwCLcBGAsYHQ/s0/pilotage%2Basso.png"" alt="représentation du pilotage de l'association hors AG">


    </div>
    {% endblock %}

templates/home/index.html.twig
{% extends 'base.html.twig' %}


{% block body %}

    {{ include('home/_menu.html.twig') }}
    <div class="ml-4">
        <h1 class="main-title ml-5 mt-5 mb-5">Bienvenue sur EkoLocal </h1>

        {% if is_granted("ROLE_ADMIN") %}
            Hi {{ app.user.username }} Dieu est parmis nous
        {% endif %}
        {% if is_granted("ROLE_USER") %}
            Hi {{ app.user.profile.firstName }}!

        {% endif %}
        {% if is_granted("ROLE_PRODUCER") %}
            Hi {{ app.user.username }}! Bienvenue à toi producteur!
        {% endif %}

        {% if is_granted ("ROLE_PRODUCER") and prodProfile is null  %}
            <p>Vous n'avez pas rempli votre profil producteur!</p>
            <li class="nav-item mr-sm-2">
                <a class="nav-link btn btn-success text-white" type="button" href="{{ path('producer_new') }}">Devenir Producteur!</a>
            </li>
        {% endif %}

        <h2> Trouvez les producteurs près de chez vous</h2>

        <p>Il y a {{ producers }} producteurs et {{ goods }} produits différents ce {{ "now"|date("d/m/Y", "Europe/Paris") }}</p>
    </div>
{% endblock %}

templates/home/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Login {% endblock %}

{% block body %}

    {{ include('home/_menu.html.twig') }}

    <div class="container">
        <div class="row">
            <div class="card-body col-5">
                {% if error %}
                    <div class="alert alert-danger">
                        {{ error.messageKey | trans( error.messagedata, 'security' ) }}
                    </div>
                {% endif %}
                <form method="POST" action="{{ path('login') }}">
                    <div class="form-group">
                        <label for="username">Identifiant</label>
                        <input id="username" name="_username" type="text" class="form-control" value="{{ last_username }}" placeholder="adresse@mail.fr">
                    </div>
                    <div class="form-group">
                        <label for="password">Mot de passe</label>
                        <input id="password" name="_password" type="password" class="form-control" placeholder="*******">
                    </div>
                    <button type="submit"
                            class="btn btn-outline-primary btn-lg">Connexion</button>
                </form>
            </div>
        </div>

            <div class="card-body">
                <div class="font-weight-bold">Si vous n'avez encore de compte :
                <a class="btn btn-success text-white ml-2" type="button" href="{{ path('user_new') }}">Créer le maintenant !</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/home/profile.html.twig
{% extends 'base.html.twig' %}

{% block title %}Vos informations:{% endblock %}

{% block body %}
    {{ include('home/_menu.html.twig') }}
    <h1>Votre profil:</h1>

    <table class="table">
        <tbody>

        <tr>
            <th>Prénom</th>
            <td>{{ profile.firstName }}</td>
        </tr>
        <tr>
            <th>Nom</th>
            <td>{{ profile.lastName }}</td>
        </tr>
        <tr>
            <th>Téléphone</th>
            <td>{{ profile.phone }}</td>
        </tr>
        <tr>
            <th>Adresse</th>
            <td>{{ profile.adress }}</td>
        </tr>
        <tr>
            <th>Code Postal</th>
            <td>{{ profile.postalCode }}</td>
        </tr>
        <tr>
            <th>Ville</th>
            <td>{{ profile.city }}</td>
        </tr>
        </tbody>
    </table>

    <a href="{{ path('profile_edit', {'id': profile.id}) }}">Modifier des informations</a>

{% endblock %}