src/Entity/Good.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use http\Exception;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\GoodRepository")
 * @Vich\Uploadable()
 */
class Good
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Producer", inversedBy="goods")
     * @ORM\JoinColumn(nullable=false)
     */
    private $producer;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\GoodsType", inversedBy="goods")
     */
    private $goods_type;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $buying_minimum;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="good_image", fileNameProperty="image")
     *
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     *
     * @var string|null
     */
    private $image;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Rate", inversedBy="rate", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $rate;


    /**
     * @ORM\Column(type="integer")
     */
    private $stock;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\LabelledType", inversedBy="goods")
     */
    private $labelled_type;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $label;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProducer(): ?Producer
    {
        return $this->producer;
    }

    public function setProducer(?Producer $producer): self
    {
        $this->producer = $producer;

        return $this;
    }

    public function getGoodsType(): ?GoodsType
    {
        return $this->goods_type;
    }

    public function setGoodsType(?GoodsType $goods_type): self
    {
        $this->goods_type = $goods_type;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getBuyingMinimum(): ?string
    {
        return $this->buying_minimum;
    }

    public function setBuyingMinimum(?string $buying_minimum): self
    {
        $this->buying_minimum = $buying_minimum;

        return $this;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|UploadedFile|null $imageFile
     * @throws \Exception
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): void
    {
        $this->image = $image;

    }

    public function getRate(): ?Rate
    {
        return $this->rate;
    }

    public function setRate(?Rate $rate): self
    {
        $this->rate = $rate;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(int $stock): self
    {
        $this->stock = $stock;

        return $this;
    }

    public function getLabelledType(): ?LabelledType
    {
        return $this->labelled_type;
    }

    public function setLabelledType(?LabelledType $labelled_type): self
    {
        $this->labelled_type = $labelled_type;

        return $this;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(string $label): self
    {
        $this->label = $label;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }
}

src/Entity/GoodsType.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\GoodsTypeRepository")
 */
class GoodsType
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $label;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Good", mappedBy="goods_type")
     */
    private $goods;

    public function __construct()
    {
        $this->goods = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(string $label): self
    {
        $this->label = $label;

        return $this;
    }

    /**
     * @return Collection|Good[]
     */
    public function getGoods(): Collection
    {
        return $this->goods;
    }

    public function addGood(Good $good): self
    {
        if (!$this->goods->contains($good)) {
            $this->goods[] = $good;
            $good->setGoodsType($this);
        }

        return $this;
    }

    public function removeGood(Good $good): self
    {
        if ($this->goods->contains($good)) {
            $this->goods->removeElement($good);
            // set the owning side to null (unless already changed)
            if ($good->getGoodsType() === $this) {
                $good->setGoodsType(null);
            }
        }

        return $this;
    }
}

src/Entity/Rate.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RateRepository")
 */
class Rate
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $price;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\UnitType")
     * @ORM\JoinColumn(nullable=false)
     */
    private $unit_type;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getUnitType(): ?UnitType
    {
        return $this->unit_type;
    }

    public function setUnitType(?UnitType $unit_type): self
    {
        $this->unit_type = $unit_type;

        return $this;
    }
}

src/Form/GoodType.php
<?php

namespace App\Form;

use App\Entity\Good;
use App\Entity\GoodsType;
use App\Entity\LabelledType;
use App\Entity\Rate;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichImageType;

class GoodType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('description')
            ->add('buying_minimum')
            ->add('imageFile', VichImageType::class, [
                'required' => false,
                'allow_delete' => true,
                'download_label' => '...',
                'download_uri' => true,
                'image_uri' => true,
                'asset_helper' => true,
            ])
            ->add('stock')
            ->add('label')
            ->add('goods_type', EntityType::class, [
                'class' => GoodsType::class,
                'choice_label' => 'label',
                'label' => 'Quel est le type de ce produit?',
                'required' => true,
                'multiple' => false
            ])
            ->add('rate', RateType::class)

            ->add('labelled_type', EntityType::class, [
                'class' => LabelledType::class,
                'choice_label' => 'label',
                'label' => "Si votre produit dispose d'un label, choisissez le:",
                'required' => false,
                'expanded' => true,
                'multiple' => false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Good::class,
        ]);
    }
}

src/Controller/GoodController.php
<?php

namespace App\Controller;

use App\Entity\Good;
use App\Entity\GoodsType;
use App\Entity\LabelledType;
use App\Entity\Producer;
use App\Entity\ProductionType;
use App\Entity\Rate;
use App\Entity\UnitType;
use App\Form\GoodType;
use App\Form\LabelledTType;
use App\Repository\GoodRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/good")
 */
class GoodController extends AbstractController
{
    /**
     * @Route("/", name="good_index", methods={"GET"})
     */
    public function index(GoodRepository $goodRepository): Response
    {
        return $this->render('good/index.html.twig', [
            'goods' => $goodRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="good_new", methods={"GET","POST"})
     * @param Request $request
     * @return Response
     */
    public function new(Request $request): Response
    {
        $good = new Good();
        
        // Requête de récupération du producteur connecté via son user_id
        $producer = $this
            ->getDoctrine()
            ->getRepository(Producer::class)
            ->findOneBy(array('user' => $this->getUser()->getId()));

        // Création du formulaire
        $form = $this->createForm(GoodType::class, $good);
        $form->handleRequest($request);

        // Validation du formulaire
        if ($form->isSubmitted() && $form->isValid()) {


            $entityManager = $this->getDoctrine()->getManager();
            $good->setProducer($producer);
            $entityManager->persist($good);
            $entityManager->flush();

            return $this->redirectToRoute('good_index');
        }

        return $this->render('good/new.html.twig', [
            'good' => $good,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="good_show", methods={"GET"})
     */
    public function show(Good $good): Response
    {
        return $this->render('good/show.html.twig', [
            'good' => $good,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="good_edit", methods={"GET","POST"})
     * @param Request $request
     * @param Good $good
     * @return Response
     */
    public function edit(Request $request, Good $good): Response
    {
        $form = $this->createForm(GoodType::class, $good);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('good_index');
        }

        return $this->render('good/edit.html.twig', [
            'good' => $good,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="good_delete", methods={"DELETE"})
     * @param Request $request
     * @param Good $good
     * @return Response
     */
    public function delete(Request $request, Good $good): Response
    {
        if ($this->isCsrfTokenValid('delete'.$good->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($good);
            $entityManager->flush();
        }

        return $this->redirectToRoute('good_index');
    }

}

templates/good/_delete_form.html.twig
<form method="post" action="{{ path('good_delete', {'id': good.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ good.id) }}">
    <button class="btn">Delete</button>
</form>

templates/good/_form.html.twig
{{ form_start(form, {'attr': {'class': 'form-horizontal'}})}}
<div class="form-row col-8">
    <div class="form-group col-md-4">{{ form_row(form.label, { 'attr': {'placeholder': 'Nom du produit'} }) }}</div>
    <div class="form-group col-md-4">{{ form_row(form.goods_type) }}
        <span>Vous ne trouvez pas le bon type? <a class="btn btn-success text-white" type="button" href="{{ path('good_newProductType') }}">Ajoutez le!</a></span>
    </div>
</div>
<div class="form-row col-8">
    <div class="form-group col-md-4">{{ form_row(form.rate.price ) }}</div>
        <div class="form-group col-md-4">{{ form_row(form.rate.unitType ) }}
        <span>Vous ne trouvez pas la bonne unité? <a class="btn btn-success text-white" type="button" href="{{ path('good_newUnit') }}">Ajoutez le!</a></span>
    </div>
</div>
<div class="form-row col-8">
    <div class="form-group col-md-4">{{ form_row(form.description, { 'attr': {'placeholder': 'Ajoutez une courte description (facultatif)'} }) }}</div>
    <div class="form-group col-md-4">{{ form_row(form.imageFile, {'attr': {'placeholder': 'Ajoutez une image (facultatif'}}) }}</div>
</div>
<div class="form-row col-8">
    <div class="form-group col-md-4">{{ form_row(form.labelled_type ) }}
        <span>Vous ne trouvez pas le bon label? <a class="btn btn-success text-white" type="button" href="{{ path('good_newLabel') }}">Ajoutez le!</a></span>
    </div>
</div>

<div><button class="btn-sm btn-outline-success">{{ button_label|default('Enregistrer') }}</button></div>

{{ form_end(form) }}

templates/good/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Good{% endblock %}

{% block body %}
    <h1>Edit Good</h1>

    {{ include('good/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('good_index') }}">back to list</a>

    {{ include('good/_delete_form.html.twig') }}
{% endblock %}

templates/good/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Good index{% endblock %}

{% block body %}
    <h1>Good index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Description</th>
                <th>Buying_minimum</th>
                <th>Image</th>
                <th>Stock</th>
                <th>Label</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for good in goods %}
            <tr>
                <td>{{ good.id }}</td>
                <td>{{ good.description }}</td>
                <td>{{ good.buyingMinimum }}</td>
                <td>{{ good.image }}</td>
                <td>{{ good.stock }}</td>
                <td>{{ good.label }}</td>
                <td>
                    <a href="{{ path('good_show', {'id': good.id}) }}">show</a>
                    <a href="{{ path('good_edit', {'id': good.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('good_new') }}">Create new</a>
{% endblock %}

templates/good/new.html.twig
{% extends 'base.html.twig' %}


{% block title %}Nouveau produit{% endblock %}

{% block body %}
    {{ include('producer/_menu.html.twig') }}
    <h1>Ajouter un produit</h1>

    {{ include('good/_form.html.twig') }}

    <a href="{{ path('good_index') }}">back to list</a>
{% endblock %}

templates/good/newLabel.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau Label{% endblock %}

{% block body %}
    <h1>Ajouter un label</h1>

    {{ form_start(form) }}
    <div class="form-group col-md-4">{{ form_row(form.label, { 'attr': {'placeholder': 'Ajoutez un nouveau label'} }) }}</div>
    <div><button class="btn-sm btn-outline-success">{{ button_label|default('Enregistrer') }}</button>
        <a class="btn-sm btn-danger text-white" type="button" href="{{ path('good_new') }}">Retour</a>
    </div>
    {{ form_end(form) }}

{% endblock %}

templates/good/newProductType.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau type de produit{% endblock %}

{% block body %}
    <h1>Ajouter un type de produit</h1>

    {{ form_start(form) }}
    <div class="form-group col-md-4">{{ form_row(form.label, { 'attr': {'placeholder': 'Ajoutez un nouveau type de produit'} }) }}</div>
    <div><button class="btn-sm btn-outline-success">{{ button_label|default('Enregistrer') }}</button>
        <a class="btn-sm btn-danger text-white" type="button" href="{{ path('good_new') }}">Retour</a>
    </div>
    {{ form_end(form) }}

{% endblock %}

templates/good/newUnit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle unité{% endblock %}

{% block body %}
    <h1>Ajouter une unité</h1>

    {{ form_start(form) }}
    <div class="form-group col-md-4">{{ form_row(form.label, { 'attr': {'placeholder': 'Ajoutez une nouvelle unité'} }) }}</div>
    <div><button class="btn-sm btn-outline-success">{{ button_label|default('Enregistrer') }}</button>
        <a class="btn-sm btn-danger text-white" type="button" href="{{ path('good_new') }}">Retour</a>
    </div>

    {{ form_end(form) }}


{% endblock %}

templates/good/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Good{% endblock %}

{% block body %}
    <h1>Good</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ good.id }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ good.description }}</td>
            </tr>
            <tr>
                <th>Buying_minimum</th>
                <td>{{ good.buyingMinimum }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ good.image }}</td>
            </tr>
            <tr>
                <th>Stock</th>
                <td>{{ good.stock }}</td>
            </tr>
            <tr>
                <th>Label</th>
                <td>{{ good.label }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('good_index') }}">back to list</a>

    <a href="{{ path('good_edit', {'id': good.id}) }}">edit</a>

    {{ include('good/_delete_form.html.twig') }}
{% endblock %}