src/Entity/Basket.php
<?php

namespace App\Entity;

use App\Repository\BasketRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BasketRepository::class)
 */
class Basket
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="float")
     */
    private $delivery_tax;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getDeliveryTax(): ?float
    {
        return $this->delivery_tax;
    }

    public function setDeliveryTax(float $delivery_tax): self
    {
        $this->delivery_tax = $delivery_tax;

        return $this;
    }
}

src/Entity/Producer.php
<?php

namespace App\Entity;

use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Exception;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProducerRepository")
 * @Vich\Uploadable()
 */
class Producer
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $siret;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firm_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firm_adress;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $firm_postal_code;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $firm_city;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="producer_image", fileNameProperty="image")
     *
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     *
     * @var string|null
     */
    private $image;


    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\ProductionType")
     * @ORM\JoinColumn(nullable=false)
     */
    private $production_type;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\User", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Good", mappedBy="producer")
     */
    private $goods;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $phone_number;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @var DateTimeInterface|null
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $tva_intracom;

    public function __construct()
    {
        $this->goods = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSiret(): ?string
    {
        return $this->siret;
    }

    public function setSiret(string $siret): self
    {
        $this->siret = $siret;

        return $this;
    }

    public function getFirmName(): ?string
    {
        return $this->firm_name;
    }

    public function setFirmName(string $firm_name): self
    {
        $this->firm_name = $firm_name;

        return $this;
    }

    public function getFirmAdress(): ?string
    {
        return $this->firm_adress;
    }

    public function setFirmAdress(string $firm_adress): self
    {
        $this->firm_adress = $firm_adress;

        return $this;
    }

    public function getFirmPostalCode(): ?string
    {
        return $this->firm_postal_code;
    }

    public function setFirmPostalCode(string $firm_postal_code): self
    {
        $this->firm_postal_code = $firm_postal_code;

        return $this;
    }

    public function getFirmCity(): ?string
    {
        return $this->firm_city;
    }

    public function setFirmCity(string $firm_city): self
    {
        $this->firm_city = $firm_city;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|UploadedFile|null $imageFile
     * @throws Exception
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): void
    {
        $this->image = $image;

    }

    public function getProductionType(): ?ProductionType
    {
        return $this->production_type;
    }

    public function setProductionType(?ProductionType $production_type): self
    {
        $this->production_type = $production_type;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Good[]
     */
    public function getGoods(): Collection
    {
        return $this->goods;
    }

    public function addGood(Good $good): self
    {
        if (!$this->goods->contains($good)) {
            $this->goods[] = $good;
            $good->setProducer($this);
        }

        return $this;
    }

    public function removeGood(Good $good): self
    {
        if ($this->goods->contains($good)) {
            $this->goods->removeElement($good);
            // set the owning side to null (unless already changed)
            if ($good->getProducer() === $this) {
                $good->setProducer(null);
            }
        }

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(string $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getUpdatedAt(): ?DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getTvaIntracom(): ?string
    {
        return $this->tva_intracom;
    }

    public function setTvaIntracom(string $tva_intracom): self
    {
        $this->tva_intracom = $tva_intracom;

        return $this;
    }
}

src/Entity/Profile.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProfileRepository")
 */
class Profile
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }
}

src/Entity/Subscription.php
<?php

namespace App\Entity;

use App\Repository\SubscriptionRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SubscriptionRepository::class)
 */
class Subscription
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="subscriptions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantity;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $frequency;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="date")
     */
    private $date_start;

    /**
     * @ORM\Column(type="date")
     */
    private $date_end;

    /**
     * @ORM\Column(type="boolean")
     */
    private $paid;

    /**
     * @ORM\Column(type="float")
     */
    private $bonus;

    /**
     * @ORM\Column(type="float")
     */
    private $tax;

    /**
     * @ORM\Column(type="float")
     */
    private $priceWithTax;

    /**
     * @ORM\ManyToOne(targetEntity=Facture::class, inversedBy="subscription")
     */
    private $facture;

    /**
     * @ORM\OneToOne(targetEntity=Facture::class, mappedBy="sub_id", cascade={"persist", "remove"})
     */
    private $factureBySubscription;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getFrequency(): ?int
    {
        return $this->frequency;
    }

    public function setFrequency(?int $frequency): self
    {
        $this->frequency = $frequency;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getDateStart(): ?\DateTimeInterface
    {
        return $this->date_start;
    }

    public function setDateStart(\DateTimeInterface $date_start): self
    {
        $this->date_start = $date_start;

        return $this;
    }

    public function getDateEnd(): ?\DateTimeInterface
    {
        return $this->date_end;
    }

    public function setDateEnd(\DateTimeInterface $date_end): self
    {
        $this->date_end = $date_end;

        return $this;
    }

    public function getPaid(): ?bool
    {
        return $this->paid;
    }

    public function setPaid(bool $paid): self
    {
        $this->paid = $paid;

        return $this;
    }

    public function getBonus(): ?float
    {
        return $this->bonus;
    }

    public function setBonus(float $bonus): self
    {
        $this->bonus = $bonus;

        return $this;
    }

    public function getTax(): ?float
    {
        return $this->tax;
    }

    public function setTax(float $tax): self
    {
        $this->tax = $tax;

        return $this;
    }

    public function getPriceWithTax(): ?float
    {
        return $this->priceWithTax;
    }

    public function setPriceWithTax(float $priceWithTax): self
    {
        $this->priceWithTax = $priceWithTax;

        return $this;
    }

    public function getFacture(): ?Facture
    {
        return $this->facture;
    }

    public function setFacture(?Facture $facture): self
    {
        $this->facture = $facture;

        return $this;
    }

    public function getFactureBySubscription(): ?Facture
    {
        return $this->factureBySubscription;
    }

    public function setFactureBySubscription(?Facture $factureBySubscription): self
    {
        // unset the owning side of the relation if necessary
        if ($factureBySubscription === null && $this->factureBySubscription !== null) {
            $this->factureBySubscription->setSubId(null);
        }

        // set the owning side of the relation if necessary
        if ($factureBySubscription !== null && $factureBySubscription->getSubId() !== $this) {
            $factureBySubscription->setSubId($this);
        }

        $this->factureBySubscription = $factureBySubscription;

        return $this;
    }
}

src/Form/SubscriptionType.php
<?php

namespace App\Form;

use App\Entity\Subscription;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SubscriptionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
          $builder
           /* ->add('quantity', NULL, [
                 'label' => 'Choisissez la quantité de paniers hebdomadaires souhaitées'
              ])
              //->add('frequency')
              // ->add('price')
              //->add('date_start')
              //->add('date_end')
              //->add('paid')
              //->add('bonus')
              // ->add('user')*/
          ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Subscription::class,
        ]);
    }
}

templates/subscription/_delete_form.html.twig
<form method="post" action="{{ path('subscription_delete', {'id': subscription.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ subscription.id) }}">
    <button class="btn">Delete</button>
</form>

templates/subscription/_form.html.twig
{{ form_start(form) }}
<div class="form-row col-8">

</div>

<label> Choisissez la quantité de paniers hebdomadaires souhaités</label>
<input type="number" id="quantity" name="quantity" min="1" value="1" onchange="CalculatePanier()">

<button class="btn">{{ button_label|default('Save') }}</button>



    {{ form_end(form) }}

templates/subscription/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Subscription{% endblock %}

{% block body %}
    <h1>Edit Subscription</h1>

    {{ include('subscription/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('subscription_index') }}">back to list</a>

    {{ include('subscription/_delete_form.html.twig') }}
{% endblock %}

templates/subscription/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Subscription index{% endblock %}

{% block body %}
    <h1>Toutes commandes</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Quantity</th>
                <th>Frequency</th>
                <th>Price</th>
                <th>Date_start</th>
                <th>Date_end</th>
                <th>Payé</th>
                <th>Bonus</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for subscription in subscriptions %}
            <tr>
                <td>{{ subscription.id }}</td>
                <td>{{ subscription.quantity }}</td>
                <td>{{ subscription.frequency }}</td>
                <td>{{ subscription.price }}</td>
                <td>{{ subscription.dateStart ? subscription.dateStart|date('Y-m-d') : '' }}</td>
                <td>{{ subscription.dateEnd ? subscription.dateEnd|date('Y-m-d') : '' }}</td>
                <td>{{ subscription.paid ? 'Oui' : 'Non' }}
                    {% if not subscription.paid %}
                        <input type="checkbox" id="{{ subscription.id }}">
                    {% endif %}
                </td>
                <td>{{ subscription.bonus }}</td>
                <td>
                    <a href="{{ path('subscription_show', {'id': subscription.id}) }}">show</a>
                    <a href="{{ path('subscription_edit', {'id': subscription.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">Aucune commande n'a été effectué pour le moment</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('controle_paiements') }}"> Valider les paiements</a>
{% endblock %}

templates/subscription/myOrders.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes commandes{% endblock %}

{% block body %}
    {{ include('home/_menu.html.twig') }}

    <h1>Mes commandes</h1>

    <table class="table">
        <thead>
        <tr>

            <th>Quantité</th>
            <th>Prix</th>
            <th>Date de la commande</th>
            <th>Date de fin de contrat</th>
            <th>Reglée</th>
            <th>Facture</th>
        </tr>
        </thead>
        <tbody>
        {% for subscription in subscriptions %}
            <tr>

                <td>{{ subscription.quantity }}</td>
                <td>{{ subscription.priceWithTax }}</td>
                <td>{{ subscription.dateStart ? subscription.dateStart|date('d M Y') : '' }}</td>
                <td>{{ subscription.dateEnd ? subscription.dateEnd|date('d M Y') : '' }}</td>
                <td>{{ subscription.paid ? '✔️' : '❌ '}}
                    {% if not subscription.paid %}
                        <button type="button" class="btn-sm btn-primary" data-toggle="modal" data-target="#Modal">❔</button>
                    {% endif %}

                </td>
                <div class="modal fade" id="Modal" tabindex="-1" role="dialog" aria-labelledby="ModalCenterTitle" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="ModalLongTitle">Information</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <div class="mt-3"> Réception et traitement en attente</div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn-sm btn-secondary" data-dismiss="modal">Fermer</button>
                            </div>
                        </div>
                    </div>
                </div>
                <td>
                    {% if subscription.paid %}
                        <a href="{{ path('subscription_show', {'id': subscription.id}) }}">facture</a>
                    {% else %}
                        ❌ <button type="button" class="btn-sm btn-primary" data-toggle="modal" data-target="#Modal">❔</button>
                    {% endif %}

                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">Vous n'avez pas encore passé commande !</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/subscription/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle commande{% endblock %}

{% block body %}
    {{ include('/home/_menu.html.twig') }}

    <h1>Passez votre commande</h1>

    <div>
        prix d'un panier de légumes : <span id="prixPanier">{{ tarif.price }}</span> €
    </div>
    <div>
        {% set deliveryTotal = tarif.price / 100 * tarif.deliveryTax%}
        frais de livraisons : <span id="prixLivraison">{{ deliveryTotal }}</span>  €
    </div>

    <div>
        Prix total de votre panier par semaine : <span id="prixTotalSemaine">{{ tarif.price + deliveryTotal }}</span> €
    </div>

    <h2> Commande pour <span id="semaines">{{ paniers }}</span> semaines pour la période {{ trimester.label }} se terminant le {{ trimester.dateEnd|date("d/m/Y")}}</h2>


    {{ include('subscription/_form.html.twig') }}

    <div>
        <span id="prixHT"></span>
        <span id="taxe"></span>
        <span id="prixTTC"></span>
    </div>


    <a href="{{ path('subscription_index') }}">back to list</a>
{% endblock %}


{% block javascripts %}
    <script>
        function CalculatePanier() {

            let quantity = document.getElementById('quantity').valueAsNumber;
            let semaines = document.getElementById('semaines').innerText;
            let prixPanier = document.getElementById('prixPanier').innerText;
            let prixLivraison = document.getElementById('prixLivraison').innerText;

            let ht = quantity * prixPanier;
            let taxe = quantity * prixLivraison;
            let ttc = ht + taxe;

            document.getElementById('prixHT').innerHTML = 'Vous avez commandés pour ' + semaines * ht + ' €';
            document.getElementById('taxe').innerHTML = semaines * taxe + ' € en frais de livraisons';
            document.getElementById('prixTTC').innerHTML = 'Prix TTC ' + semaines * ttc + ' €';
        }


    </script>

{% endblock %}

templates/subscription/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Subscription{% endblock %}

{% block body %}

    <div class="container mt-2">

        <div class="row">
            <div class="col-8">
                <div id="nomAsso" style="font-weight: bolder; font-size: x-large">{{ asso.assoName }}</div>
                <div id="adresseAsso">{{ asso.assoAdress }}</div>
                <div id="villeAsso" style="font-weight: lighter">{{ asso.assoPostalCode }} {{ asso.assoCity }}</div>
                <div id="telAsso" style="font-weight: lighter">{{ asso.phoneNumber }}</div>
                <div id="mailAsso" style="font-weight: lighter">{{ asso.email }}</div>
            </div>
            <div class="col-4 ">
                <span id="noFacture" style="font-weight: bold; font-size: larger">Facture n° {{ facture.reference }} </span>
            </div>
        </div>

        <div class="row mt-4 ml-1">
            <div class="col-3" style="font-weight: bold; background-color: #7DA0B1">
                <div class="row mt-2">
                    <div class="ml-2">
                        <div id="dateFacture">Date de facture : </div>
                        <div id="refFacture">Réf. de facture : </div>
                        <div id="paiementFacture">Paiement dû : </div>
                    </div>
                    <div class="ml-2">
                        <div id="dateFacture">{{ facture.date|date('d/m/Y') }} </div>
                        <div id="refFacture">{{ facture.reference }}</div>
                        <div id="paiementFacture">{{ facture.date|date('d/m/Y') }}</div>
                    </div>
                </div>

            </div>
            <div class="col-3"></div>
            <div class="col-5 mt-2 mb-2">
                <div id="destinataire" style="font-weight: bold"> Destinataire :</div>
                <div id="nomDestinataire"> {{ subscription.user.profile.firstName}} {{ subscription.user.profile.lastName}} </div>
                <div id=adresseDestinataire"> {{ subscription.user.profile.adress }} </div>
                <div id="villeDestinataire">{{ subscription.user.profile.postalCode }} {{ subscription.user.profile.city }}</div>
            </div>
        </div>
        <table class="table table-striped table-bordered mt-4">
            <thead>
            <tr style="text-align: center">
                <th scope="col" >Quantité</th>
                <th scope="col">Description</th>
                <th scope="col">Prix unitaire HT</th>
                <th scope="col">Prix unitaire TTC</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th scope="row" style="text-align: center">{{ facture.quantity }}</th>
                <td style="text-align: center">{{ facture.description }}</td>
                <td style="text-align: right">{{ (panier.price /(1+(facture.tva/100)))|round(2,'common') }} €</td>
                <td style="text-align: right">{{ panier.price }} €</td>
            </tr>

            </tbody>
        </table>

    </div>
    <table class="table table-bordered table-striped col-2 offset-md-8">
        <tr>
            <th>Total Hors Taxe</th>
            <th style="font-weight: normal; text-align: right">{{ facture.priceHt}} €</th>
        </tr>
        <tr>
            <th>TVA à {{ facture.tva}} %</th>
            <th style="font-weight: normal; text-align: right">{{ facture.priceTtc - facture.priceHt}} €</th>
        </tr>
        <tr>
            <th>Livraison</th>
            <th style="font-weight: normal; text-align: right">{{ facture.deliveryTax}} €</th>
        </tr>
        <tr>
            <th>Total TTC en euros</th>
            <th style="text-align: right">{{ facture.priceTtc}} €</th>
        </tr>
    </table>




    <div id="footer" class="container">
        <div class="row">
            <div class="mr-2 font-weight-bold">
                <div class="">SIRET</div>
                <div class="">N° TVA intracom</div>
            </div>
            <div class="ml-2">
                <div class="">{{ asso.siret }}</div>
                <div class="">{{ asso.tvaIntracom }}</div>
            </div>

        </div>


    </div>

    <a class=" btn btn-success text-white ml-4" type="button" href="{{ path('home') }}">Retour</a>


{% endblock %}